#ifndef _CONFIGDEFS_
#define _CONFIGDEFS_ 1

#define DYNAMORIO_DEFINES "-DINTERNAL -DDEBUG -DDRGUI_DEMO -DARM -DLINUX -DCLIENT_INTERFACE -DAPP_EXPORTS -DKSTATS -DDR_DO_NOT_DEFINE_uint -DDR_DO_NOT_DEFINE_ushort -DDR__Bool_EXISTS -DX86 -DASSEMBLE_WITH_GAS -DHAVE_PROC_MAPS -DHAVE_TLS -DHAVE_SIGALTSTACK -DDYNAMORIO_IR_EXPORTS -DCUSTOM_TRACES -DCLIENT_SIDELINE -DDR_APP_EXPORTS -DDEBUG_MEMORY -DSTACK_GUARD_PAGE -DHEAP_ACCOUNTING -DDEADLOCK_AVOIDANCE -DSHARING_STUDY -DHASHTABLE_STATISTICS"

#endif /* _CONFIGDEFS_ */
